steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "bench/Dockerfile",
           "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/jy-crpg-bench:$_TAG",
           "."]
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/jy-crpg-bench:$_TAG"
substitutions:
  _TAG: v1
options:
  machineType: E2_HIGHCPU_8
timeout: 1800s
