"""The four-hour sessions, one row per session: the minute of the last key,
the actions sent, the minute at which each replay-visible milestone of the
opening was first reached, and the number of milestones credited. No session
entered a fight, so the campaign milestones have no column. The crossing is timed by the
service from the first black frame, the other milestones by the replay and its
keypress timeline. Prints tables/long.tex; preflight.py writes it.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import field  # noqa: E402

COLUMNS = (("Map", "crossing"), ("Item", "obtained"), ("Scene", "scene"), ("Hermit", "hermit"),
           ("Compass", "compass"), ("Companion", "recruited"))

rows = field.load_long()
if not rows:
    sys.exit("no four-hour session on record")


def first_second(e, name):
    if name == "recruited":
        return None if e.get("recruited_minute") is None else e["recruited_minute"] * 60 / e["speed"]
    if name == "scene":
        m = (e.get("scenes") or {}).get("first_minute")
        return None if m is None else m * 60 / e["speed"]
    p = e.get(name) or {}
    return None if not p.get("minutes") else p["minutes"][0] * 60 / e["speed"]


def line(r):
    e = r.get("replay")
    tl_path = os.path.join(HERE, "timelines", r["id"] + ".json")
    if not e or not os.path.exists(tl_path):
        sys.exit(f"{r['agent']} {r['id']}: no replay reading or timeline")
    tl = json.load(open(tl_path, encoding="utf-8"))
    e = dict(e, speed=tl["speed"])
    last = tl["marks"][-1]["t"] * tl["speed"] / 60 if tl["marks"] else 0.0
    cells = []
    for _, name in COLUMNS:
        if name == "crossing":
            minute = r["exit_secs"] / 60 if r.get("exit_secs") is not None else None
        else:
            sec = first_second(e, name)
            minute = None if sec is None else sec * tl["speed"] / 60
        cells.append("--" if minute is None else "%.0f" % minute)
    return field.rungs_reached(r), r["agent"], last, r["actions"], cells


out = sorted((line(r) for r in rows), key=lambda x: (-x[0], x[1]))
print("% generated by figures/emit_long.py from the four-hour sessions; do not hand-edit")
print("\\begin{tabular}{@{}l" + "r" * (3 + len(COLUMNS)) + "@{}}")
print("\\toprule")
print("Model & Last key & Actions & " + " & ".join(c for c, _ in COLUMNS) + " & Milestones \\\\")
print("\\midrule")
for reached, agent, last, actions, cells in out:
    print("\\texttt{%s} & %.0f & %d & %s & %d \\\\" % (agent, last, actions, " & ".join(cells), reached))
print("\\bottomrule")
print("\\end{tabular}")
