"""The fourteen books and the compass, as the save decoder names them.

    python3 figures/emit_books.py > tables/books.tex

The names and item ids are read from server/save_state.py, where a test
checks them against the item table the release ships, so the appendix cannot
list a book the decoder does not look for.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "..", "server", "save_state.py")
text = open(SRC, encoding="utf-8").read()
ids = re.search(r"BOOK_IDS = tuple\(range\((\d+), (\d+)\)\)", text)
first, last = int(ids.group(1)), int(ids.group(2)) - 1
block = text[text.index("BOOK_NAMES = ("):]
names = re.findall(r'"([^"]+)"', block[:block.index(")")])
assert len(names) == last - first + 1 == 14, (len(names), first, last)

print("% generated by figures/emit_books.py from server/save_state.py")
print("\\newcommand{\\BookFirst}{%d}" % first)
print("\\newcommand{\\BookLast}{%d}" % last)
print("\\newcommand{\\BookCount}{%d}" % len(names))
print("\\newcommand{\\booklist}{\\game{" + "、".join(names) + "}}")
compass_id = int(re.search(r"COMPASS_ID = (\d+)", text).group(1))
compass_name = re.search(r'COMPASS_NAME = "([^"]+)"', text).group(1)
print("\\newcommand{\\CompassId}{%d}" % compass_id)
print("\\newcommand{\\CompassName}{\\game{%s}}" % compass_name)
