"""The fourteen books and the compass, as the save decoder names them.

    python3 figures/emit_books.py > tables/books.tex

The names and item ids are read from server/save_state.py, where a test
checks them against the item table the release ships, so the appendix cannot
list a book the decoder does not look for. \booktable holds the glossary rows
of the books, each with the English title of the novel; a book without a title
in TITLES stops the script.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "..", "server", "save_state.py")
text = open(SRC, encoding="utf-8").read()
ids = re.search(r"BOOK_IDS = tuple\(range\((\d+), (\d+)\)\)", text)
first, last = int(ids.group(1)), int(ids.group(2)) - 1
block = text[text.index("BOOK_NAMES = ("):]
names = re.findall(r'"([^"]+)"', block[:block.index(")")])
assert len(names) == last - first + 1 == 14, (len(names), first, last)
TITLES = {
    "飛狐外傳": "The Young Flying Fox", "雪山飛狐": "Fox Volant of the Snowy Mountain",
    "連城訣": "A Deadly Secret", "天龍八部": "Demi-Gods and Semi-Devils",
    "射鵰英雄傳": "The Legend of the Condor Heroes", "白馬嘯西風": "White Horse Neighs in the Western Wind",
    "鹿鼎記": "The Deer and the Cauldron", "笑傲江湖": "The Smiling, Proud Wanderer",
    "書劍恩仇錄": "The Book and the Sword", "神鵰俠侶": "The Return of the Condor Heroes",
    "俠客行": "Ode to Gallantry", "倚天屠龍記": "The Heaven Sword and Dragon Saber",
    "碧血劍": "Sword Stained with Royal Blood", "鴛鴦刀": "Blade-dance of the Two Lovers",
}
missing = [n for n in names if n not in TITLES]
assert not missing, "no English title for " + ", ".join(missing)

print("% generated by figures/emit_books.py from server/save_state.py")
print("\\newcommand{\\BookFirst}{%d}" % first)
print("\\newcommand{\\BookLast}{%d}" % last)
print("\\newcommand{\\BookCount}{%d}" % len(names))
print("\\newcommand{\\booktable}{" + " ".join("%s & \\game{%s} \\\\" % (TITLES[n], n) for n in names) + "}")
compass_id = int(re.search(r"COMPASS_ID = (\d+)", text).group(1))
print("\\newcommand{\\CompassId}{%d}" % compass_id)

# The defaults the service runs with, read from the code that sets them so the
# paper cannot state a budget or a replay speed the deployment does not use.
broker = open(os.path.join(HERE, "..", "..", "..", "bench", "broker.py"), encoding="utf-8").read()
run_seconds = int(re.search(r'"QUNXIA_RUN_SECONDS", "(\d+)"', broker).group(1))
assert run_seconds % 60 == 0, run_seconds
render = open(os.path.join(HERE, "..", "..", "..", "bench", "render.py"), encoding="utf-8").read()
speed = float(re.search(r"^DEFAULT_SPEED = ([0-9.]+)", render, re.M).group(1))
print("\\newcommand{\\DefaultBudgetSec}{%d}" % run_seconds)
print("\\newcommand{\\DefaultBudgetMin}{%d}" % (run_seconds // 60))
print("\\newcommand{\\DefaultReplaySpeed}{%g}" % speed)
