"""The replay-visible milestones in actions and minutes.

For every session that reached a milestone, the number of actions the model
had sent when the panel first appeared (the crossing from the first black
frame) and the minute of play, both from the replay and its keypress timeline;
the table reports how many sessions reached each milestone and the median of
each measure over them. Prints tables/milestones.tex; preflight.py writes it.
"""
import json
import os
import statistics as st
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import field  # noqa: E402

ROWS = (("reached the world map", "crossing"), ("picked up an item", "obtained"),
        ("entered a scene", "scene"), ("spoke with the hermit", "hermit"), ("held the compass", "compass"),
        ("recruited a companion", "recruited"), ("entered a fight", "battle"),
        ("fought to the end", "defeat"))

rows = [r for r in field.played(field.load_runs(dedup=False)) if not field.is_random(r["agent"])]


def first_second(e, name):
    if name == "crossing":
        return e.get("first_black_second")
    if name == "recruited":
        return None if e.get("recruited_minute") is None else e["recruited_minute"] * 60 / e["speed"]
    if name == "scene":
        m = (e.get("scenes") or {}).get("first_minute")
        return None if m is None else m * 60 / e["speed"]
    p = e.get(name) or {}
    return None if not p.get("minutes") else p["minutes"][0] * 60 / e["speed"]


def actions_by(marks, second):
    return sum(1 for m in marks if m["t"] <= second)


out = []
for label, name in ROWS:
    acts, mins = [], []
    for r in rows:
        e = r.get("replay")
        tl_path = os.path.join(HERE, "timelines", r["id"] + ".json")
        if not e or not os.path.exists(tl_path):
            continue
        tl = json.load(open(tl_path, encoding="utf-8"))
        e = dict(e, speed=tl["speed"])
        sec = first_second(e, name)
        if sec is None:
            continue
        acts.append(actions_by(tl["marks"], sec))
        mins.append(sec * tl["speed"] / 60)
    if not acts:
        sys.exit(f"no session reached {label!r}; drop the row or check the scan")
    out.append((label, len(acts), st.median(acts), st.median(mins)))

print("% generated by figures/emit_milestones.py from the replays and timelines; do not hand-edit")
print("\\begin{tabular}{@{}lrrr@{}}")
print("\\toprule")
print("Milestone & Sessions & Median actions & Median minute \\\\")
print("\\midrule")
for label, n, a, m in out:
    print("%s & %d & %.0f & %.0f \\\\" % (label, n, a, m))
print("\\bottomrule")
print("\\end{tabular}")
