"""Every battle of the sessions in the paper, one row each: the model, the
budget, the party, the minutes it began and ended, the outcome, the actions
and keys the model sent while it lasted and the share of confirm keys. Prints
tables/battles.tex; preflight.py writes it.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import field

PARTY = {1: "hero", 2: "hero, Tian Boguang"}


def all_battles():
    rows = [r for r in field.played(field.load_runs(dedup=False))] + field.load_long()
    out = []
    for r in rows:
        for b in field.battles(r):
            out.append((r, b))
    return sorted(out, key=lambda rb: (rb[0]["budget"], rb[0]["agent"], rb[0]["id"], rb[1]["start"]))


def main():
    print("% generated by figures/emit_battles.py")
    print("\\begin{tabular}{@{}lrlrrlrrr@{}}")
    print("\\toprule")
    print("Model & Budget & Party & Began & Ended & Outcome & Actions & Keys & Confirm \\\\")
    print("\\midrule")
    for r, b in all_battles():
        print("% battle-session: " + r["id"])
        print("\\texttt{%s} & %d\\,min & %s & %.1f & %.1f & %s & %d & %d & %.0f\\,\\%% \\\\" % (
            r["agent"], r["budget"] // 60, PARTY[b["party"]], b["start"], b["end"], b["outcome"],
            b["actions"], b["keys"], 100 * b["confirm"]))
    print("\\bottomrule")
    print("\\end{tabular}")


if __name__ == "__main__":
    main()
